baseurl: "" # the subpath of your site, e.g. blog/
url: "https://woojinjeonkr.github.io/" # the base hostname & protocol for your site, e.g. http://example.com/

title: Woojin's Devblog | Personal Blog Template
description: >- # this means to ignore newlines until "baseurl:"
  This development blog features articles on academic or personal study materials, 
  topics learned or reviewed while working, 
  and subjects related to development that personally pique interest.

# codepen
codepen_username: calomys

#################### Comment Section (Disqus) ################
# disqus_shortname: "" # Add your shortname for Disqus Comment. For example : mr-brown

# Scss Directory
sass:
  sass_dir: assets/scss
  style: compressed

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-youtube
  - jekyll-gist
  - jekyll-time-to-read

# pagination settings
paginate: 6
paginate_path: "/page/:num"

# include
include:
  - _pages
  - _authors

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

  - scope:
      path: "_authors"
    values:
      permalink: /author/:basename:output_ext
      layout: author

  - scope:
      path: ""
      type: "posts"
    values:
      permalink: post/:title:output_ext
      layout: post

  - scope:
      path: ""
      type: "tags"
    values:
      permalink: /tag/:slug
      layout: tags

# Tags
tag_page_dir: tag
tag_page_layout: tags
tag_permalink_style: pretty

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
