########################### Navigation ###################################
menu:
  # main menu
  main:
    - { name: Home, url: "/" }
    # - { name: Contact, url: "contact.html" }
    - { name: Tools, url: "tools.html" }
    # - { name: Timeline, url: "timeline.html" }

  ##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

  ##########################

  # Footer menu
  footer:
    - { name: Home, url: "/" }
    # - { name: Contact, url: "contact.html" }
    - { name: Tools, url: "tools.html" }

######################### Default Parameters ###########################

# logo
logo: "/assets/images/logo.png"
# meta data
author: "Woojin JEON"
description: "Owner of this blog"
# google analitycs ID
google_analitycs_id: G-XPVW058LPJ # your id
# contact form action
# contact_form_action: "#" # contact form works with : https://formspree.io
# copyright
copyright: "Copyright &copy; 2022 Designed and Developed by [Themefisher](https://themefisher.com) and Customized by [Woojin JEON](https://github.com/WoojinJeonkr)"

# preloader
preloader:
  enable: true
  preloader: "" # use png, jpg, svg or gif format

# search
search:
  enable: true

############################## Social Site ##########################
social:
  - name: "github"
    icon: "ti-github" # themify icon pack https://themify.me/themify-icons
    link: "https://github.com/WoojinJeonkr"

  # - name: "linkedin"
  #   icon: "ti-linkedin" # themify icon pack https://themify.me/themify-icons
  #   link: "#"
